
@localhost =  http://localhost:8000/api

### HEALTH CHECK
GET {{localhost}}/

### fetch all users
GET {{localhost}}/users

### fetch a user
GET {{localhost}}/users/8B798F98-6BAF-F011-A791-4C496CCEA2E2


### create a user
POST {{localhost}}/users
content-type: application/json

{
    "firstName": "firstname",
    "lastName": "lastname",
    "email": "test@gmail.com"
}

### LOGIN
POST {{localhost}}/users 
content-type: application/json
Authorization: Bearer your_token_here

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### UPDATE A USER
PUT {{localhost}}/users/8B798F98-6BAF-F011-A791-4C496CCEA2E2
content-type: application/json

{
   "firstName": "firstname-UPDATE"
}

### DELETE A USER
DELETE {{localhost}}/users/8B798F98-6BAF-F011-A791-4C496CCEA2E2

### SEARCH USERS
GET {{localhost}}/users/search
    ?query=sample
    &limit=5
    
### LIST COMMENTS WITH PAGINATION
GET {{localhost}}/users
    ?page=2
    &pageSize=10